server:
   port: 8761
eureka: 
   client: 
      registerWithEureka: false #是否將自己註冊到eureka server
      fetchRegistry: false #是否從eureka server取得註冊資訊進行同步(叢集需求)
      serviceUrl: 
         defaultZone: http://user:password123@localhost:8761/eureka/ #欲註冊與查詢之eureka server地址
security:
   basic:
      enabled: true #以HTTP認證
   user:
      name: user
      password: password123    